#!C:\MLOPS Projects\Kidney_Disease_Project\Kidney_Disease_Clasification_MLFlow_DVC\kidney_disease\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
